package dsag;

import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Calendar;

/*
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ADDCUS.java
 *
 * Created on Jan 1, 2002, 12:29:53 AM
 */

/**
 *
 * @author mukesh
 */
public class ADDCUS extends javax.swing.JFrame {

    /** Creates new form ADDCUS */
    public ADDCUS() {
        initComponents();
    }
 Object abc() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d1 = new datechooser.beans.DateChooserDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        a2 = new javax.swing.JTextArea();
        t1 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        c1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        t8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        d11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Add Customer");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(230, 20, 136, 31);

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("COUNTRY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 230, 73, 17);

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID PROOF");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 280, 80, 17);

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID NUMBER");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 320, 86, 17);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MARITAL STATUS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 370, 131, 17);

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ROOM NUMBER");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 420, 117, 17);

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ARRIVAL DATE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(450, 80, 112, 30);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDRESS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 130, 72, 17);

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CITY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 180, 100, 20);

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CUSTOMER NAME");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 80, 134, 17);

        a2.setColumns(15);
        a2.setRows(2);
        a2.setTabSize(5);
        jScrollPane1.setViewportView(a2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 120, 150, 42);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(270, 80, 150, 20);

        t7.setText(" ");
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        getContentPane().add(t7);
        t7.setBounds(270, 370, 150, 20);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6);
        t6.setBounds(270, 310, 150, 20);
        getContentPane().add(t3);
        t3.setBounds(270, 180, 150, 20);

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(270, 260, 150, 20);

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(270, 220, 150, 20);

        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(270, 410, 150, 20);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 290, 120, 31);

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(500, 340, 120, 31);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setText("<<BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 400, 130, 29);

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        getContentPane().add(t8);
        t8.setBounds(270, 450, 150, 20);

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MOBILE NUMBER");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 460, 127, 17);

        d11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsag/UJ.jpg"))); // NOI18N
        getContentPane().add(d11);
        d11.setBounds(0, -90, 720, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO addcustomer your handling code here:
}//GEN-LAST:event_t1ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO addcustomer your handling code here:
}//GEN-LAST:event_t7ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO addcustomer your handling code here:
}//GEN-LAST:event_t5ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO addcustomer your handling code here:
}//GEN-LAST:event_t4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try 
        {
             
            String name=t1.getText();
            String address=a2.getText();
            String city=t3.getText();
            String country=t4.getText();
            String id_proof=t5.getText();
            int id_no=Integer.parseInt(t6.getText());
            String ms=t7.getText();

        
  
   
            Calendar d;
            d = d1.getSelectedDate();
            int date=d.get(d.DAY_OF_MONTH);
            int year=d.get(d.YEAR);
            int month=d.get(d.MONTH)+1;
            String dat=Integer.toString(date);
            String y=Integer.toString(year);
            String m=Integer.toString(month);
            String dob=y+"-"+m+"-"+dat;
          int r_no=(Integer)(c1.getSelectedItem());
            //  String ad=t10.getText();



            // pass=p1.getText();
            //name=t1.getText();

            Class.forName("java.sql.DriverManager");
            Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root","RRMPS");
            Statement s=(Statement)c.createStatement();
          
            String query="insert into customer_details values('"+name+"','"+address+"','"+city+"','"+country+"','"+id_proof+"',"+id_no+",'"+ms+"',"+r_no+",'"+dob+"','"+t8.getText()+"');";
             
          //  JOptionPane.showMessageDialog(null,query);
            s.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"customer has been added");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
      
        // TODO addcustomer your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        t1.setText("");
        t7.setText("");
        t3.setText("");
        a2.setText("");
        t8.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");


        // TODO addcustomer your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new menu().setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_c1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 try
 {

        Class.forName("java.sql.DriverManager");
        Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root","RRMPS");
        Statement stmt=(Statement)c.createStatement();
        String s="select * from Room_details;";
        ResultSet rs=stmt.executeQuery(s);
        while( rs.next())
         {
         c1.addItem(Integer.parseInt(rs.getString("r_no")));
           }
            
 }
 catch(Exception e)
 {
   JOptionPane.showMessageDialog(null,e);
 }// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDCUS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea a2;
    private javax.swing.JComboBox c1;
    private datechooser.beans.DateChooserDialog d1;
    private javax.swing.JLabel d11;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables

}
