package dsag;


import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CBILL.java
 *
 * Created on Jan 4, 2015, 1:59:47 AM
 */

/**
 *
 * @author mukesh
 */
public class CBILL extends javax.swing.JFrame {

    /** Creates new form CBILL */
    public CBILL() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24));
        jLabel1.setText("YOUR BILL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 20, 92, 31);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel2.setText("CUSTOMER NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 170, 134, 17);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 0, 0);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 190, 110, 29);

        t1.setEditable(false);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(270, 170, 120, 20);

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel5.setText("NET PAYABLE AMOUNT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 240, 174, 17);

        t4.setEditable(false);
        getContentPane().add(t4);
        t4.setBounds(270, 240, 120, 20);

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel7.setText("ID NUMBER");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 100, 86, 17);

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(270, 100, 130, 20);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        jButton2.setText("<<BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(447, 260, 110, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsag/pOOOO.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 670, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public javax.swing.JTextField abc()
{
    return t4;
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try
{
            Class.forName("java.sql.DriverManager");
            Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root","RRMPS");
            Statement s=(Statement)c.createStatement();
            String q="select * from customer_details where id_number="+t5.getText()+";";
ResultSet rs=s.executeQuery(q);
while(rs.next())
{
    String title=rs.getString("customer_name");
    t1.setText(title);




        }
        }
        catch(Exception e) {

            JOptionPane.showMessageDialog(this,e.getMessage());
    }
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

        private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_t1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.dispose();
new menu().setVisible(true);            // TODO add your handling code here:
        }//GEN-LAST:event_jButton2ActionPerformed

        private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_t5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CBILL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables

}
