package dsag;

import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Calendar;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * check.java
 *
 * Created on Jan 1, 2002, 12:15:09 AM
 */

/**
 *
 * @author mukesh
 */
public class check extends javax.swing.JFrame {

    /** Creates new form check */
    public check() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        c1 = new datechooser.beans.DateChooserCombo();
        t7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel14.setFont(new java.awt.Font("Impact", 0, 24));
        jLabel14.setText("CHECKOUT");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(230, 30, 99, 31);

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel11.setText("ID NUMBER");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 150, 86, 20);
        getContentPane().add(c1);
        c1.setBounds(380, 50, 155, 20);

        t7.setToolTipText("ENTER YOUR ID NUMBER HERE");
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        getContentPane().add(t7);
        t7.setBounds(250, 150, 110, 20);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel3.setText("CUSTOMER NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 190, 134, 17);

        t2.setEditable(false);
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(250, 190, 110, 20);

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel12.setText("ROOM NUMBER");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(67, 240, 130, 17);

        c2.setEnabled(false);
        getContentPane().add(c2);
        c2.setBounds(250, 240, 110, 20);

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel13.setText("ARRIVAL DATE");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 290, 112, 17);

        t1.setEditable(false);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(250, 280, 110, 20);

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel4.setText("MOBILE NUMBER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 330, 127, 17);

        t9.setEditable(false);
        getContentPane().add(t9);
        t9.setBounds(250, 330, 110, 20);

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        jButton6.setText("CLEAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(470, 280, 160, 31);

        b2.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        b2.setText("SEARCH");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(450, 340, 160, 31);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        jButton1.setText("CHECKOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 390, 160, 31);

        jLabel2.setText("ENTER YOUR ID NUMBER HERE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 120, 180, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsag/HUI.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 700, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
t7.setText("");
t2.setText("");
c2.setSelectedItem("");
t1.setText("");
t9.setText("");
// TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        int id_no=Integer.parseInt(t7.getText());

        try {

            Class.forName("java.sql.DriverManager");

            Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root","RRMPS");

            Statement s=(Statement)c.createStatement();
            String quer="select * from customer_details where id_number="+id_no+";";

            ResultSet rs=s.executeQuery(quer);


            rs.next();
            String cu=rs.getString("customer_Name");



/*String b=rs.getString("address");
String d= rs.getString("city");
String e1= rs.getString("country");
String f= rs.getString("id_Proof");


String g= rs.getString("marital_status");*/
            String rno=rs.getString("room_number");

            String i=rs.getString("arrival_date");
            String mbno=rs.getString("mobile_no");
            t2.setText(cu);
            //a2.append(b);
            // t3.setText(d);
            // t4.setText(e1);
            //t5.setText(f);
            //t7.setText(g);
            c2.addItem(rno);
            t1.setText(i);
            t9.setText(mbno);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }// TODO add your handling code here:s
        // TODO add your handling code here:
}//GEN-LAST:event_b2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
         
                  try
{
                      String s=t7.getText();
Class.forName("java.sql.DriverManager");
Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","RRMPS");
//Statement s2=(Statement)c.createStatement();
Statement s3=(Statement)c.createStatement();
Statement s4=(Statement)c.createStatement();
Statement s5=(Statement)c.createStatement();
Statement s6=(Statement)c.createStatement();
//Calendar d=c1.getSelectedDate();
   String q3="Select YEAR(CURDATE());";
   ResultSet rs3=s3.executeQuery(q3);
rs3.next();
   int cy=rs3.getInt("YEAR(CURDATE())");
   String q4="Select YEAR(arrival_date) FROM customer_details WHERE id_number="+s+";";
   ResultSet rs4=s4.executeQuery(q4);
rs4.next();
   int cy1=rs4.getInt("YEAR(arrival_date)");
   int diffy=cy-cy1;
   int d1=(diffy*365)+1;

   String q5="Select DAYOFYEAR(CURDATE());";
   ResultSet rs5=s5.executeQuery(q5);
rs5.next();
   int cy2=rs5.getInt("DAYOFYEAR(CURDATE())");

   String q6="Select DAYOFYEAR(Arrival_date) FROM customer_details WHERE id_number="+s+";";
   ResultSet rs6=s6.executeQuery(q6);
rs6.next();
   int cy3=rs6.getInt("DAYOFYEAR(arrival_date)");

   int diff2=cy2-cy3;
    int df3=d1+diff2;
    int net=df3*2000;
    String net_amt=Integer.toString(net);
    JOptionPane.showMessageDialog(null,"  total bill to be paid  "+" Rs."+ net );


                               //  int dt=(date)(c1.getSelectedDate());
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
c1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new check().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2;
    private datechooser.beans.DateChooserCombo c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables

}
