package dsag;


import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CUSTDET.java
 *
 * Created on Jan 1, 2002, 12:14:31 AM
 */

/**
 *
 * @author mukesh
 */
public class CUSTDET extends javax.swing.JFrame {

    /** Creates new form CUSTDET */
    public CUSTDET() {
        initComponents();
    }

    Object abc() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        a2 = new javax.swing.JTextArea();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        d1 = new javax.swing.JComboBox();
        t8 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Impact", 0, 28));
        jLabel11.setText("Customer Details");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 20, 197, 35);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel2.setText("CUSTOMER NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 80, 134, 17);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel3.setText("ADDRESS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 130, 72, 17);

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel4.setText("CITY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 180, 33, 17);

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel5.setText("COUNTRY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 220, 73, 17);

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel6.setText("ID PROOF");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 260, 72, 17);

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel7.setText("ID NUMBER");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 300, 86, 20);

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel8.setText("MARITAL STATUS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 340, 131, 17);

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel9.setText("ROOM NUMBER");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 380, 117, 17);

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel10.setText("ARRIVAL DATE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 420, 112, 17);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(200, 80, 130, 20);

        a2.setColumns(15);
        a2.setRows(2);
        a2.setTabSize(5);
        jScrollPane1.setViewportView(a2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 120, 126, 42);
        getContentPane().add(t3);
        t3.setBounds(200, 180, 130, 20);

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(200, 220, 130, 20);

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(200, 260, 130, 20);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6);
        t6.setBounds(200, 300, 130, 20);

        t7.setText(" ");
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        getContentPane().add(t7);
        t7.setBounds(200, 340, 130, 20);

        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        getContentPane().add(d1);
        d1.setBounds(200, 370, 130, 20);
        getContentPane().add(t8);
        t8.setBounds(200, 450, 130, 20);

        b1.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        b1.setText("MODIFY");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
        });
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(420, 270, 130, 31);

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(420, 320, 130, 31);

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel12.setText("MOBILE NUMBER");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 460, 127, 17);
        getContentPane().add(d2);
        d2.setBounds(199, 410, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsag/JB.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t4ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t5ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t6ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t7ActionPerformed
public javax.swing.JTextField  avisha()
{
    return t6;
}
    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed

        // TODO add your handling code here:
}//GEN-LAST:event_d1ActionPerformed

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
        d1.removeAllItems();
        String a="";
        try {
            Class.forName("java.sql.DriverManager");
            Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root","RRMPS");
            Statement s=(Statement)c.createStatement();
            String query="select * from room_details;";
            ResultSet rs=s.executeQuery(query);
            while(rs.next()) {
                a=rs.getString("R_NO");
                d1.addItem(a);
            }
        } catch(Exception e) {
        }        // TODO add your handling code here:
}//GEN-LAST:event_b1MouseEntered

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed


        //JOptionPane.showMessageDialog(null,query);    // TODO add your handling code here:



        try {
            String name=t1.getText();
            String address=a2.getText();
            String city=t3.getText();
            String country=t4.getText();
            String id_proof=t5.getText();
            int id_no=Integer.parseInt(t6.getText());
            String ms=t7.getText();
            int mob_no=Integer.parseInt(t8.getText());
           //String dat=Integer.toString(date);
           String dob=d2.getText(); String r_no=(String)d1.getSelectedItem();
            Class.forName("java.sql.DriverManager");
            Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root","RRMPS");
            Statement s=(Statement)c.createStatement();
            Statement s1=(Statement)c.createStatement();
            String query="insert into customer_details values('"+name+"','"+address+"','"+city+"','"+country+"','"+id_proof+"',"+id_no+",'"+ms+"',"+r_no+",'"+dob+"',"+mob_no+");";
            String query1="delete from customer_details;";
            s1.executeUpdate(query1);
            //JOptionPane.showMessageDialog(null,query);
            s.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"customer has been added");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }


        // TODO add your handling code here:
}//GEN-LAST:event_b1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        t1.setText("");
        t7.setText("");
        t3.setText("");
        a2.setText("");
        t8.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        this.dispose();
        new already().setVisible
                (true);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
        {
         String Id=t6.getText();


        Class.forName("java.sql.DriverManager");
            Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root","RRMPS");
            Statement s=(Statement)c.createStatement();
            String quer="Select * from customer_details where Id_number="+Id+";";
            JOptionPane.showMessageDialog(null,quer);
            ResultSet rs=s.executeQuery(quer);
            rs.next();
            
            t1.setText(rs.getString("Customer_name"));
            a2.append(rs.getString("Address"));
            t3.setText(rs.getString("city"));
            t4.setText(rs.getString("country"));
            t5.setText(rs.getString("Id_proof"));
            t6.setText(Integer.toString(rs.getInt("id_number")));
            t7.setText(rs.getString("marital_status"));
            d1.addItem(Integer.toString(rs.getInt("room_number")));
d2.setText(rs.getString("arrival_date"));
t8.setText(Integer.toString(rs.getInt("mobile_no")));
        }
        catch(Exception e)
        {
JOptionPane.showMessageDialog(null,e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUSTDET().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea a2;
    private javax.swing.JButton b1;
    private javax.swing.JComboBox d1;
    private javax.swing.JTextField d2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables

    class abc {

      
        public abc() {
        }
    }

}
