package dsag;

import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * items.java
 *
 * Created on Jan 1, 2002, 1:10:27 AM
 */

/**
 *
 * @author mukesh
 */
public class items extends javax.swing.JFrame {

    /** Creates new form items */
    public items() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(t1);
        t1.setBounds(280, 130, 160, 20);
        getContentPane().add(t2);
        t2.setBounds(280, 190, 160, 20);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel1.setText("ITEM NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 130, 87, 17);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel2.setText("COST");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 200, 40, 17);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 150, 90, 31);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24));
        jLabel3.setText("ADD ITEMS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 30, 99, 31);

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel4.setText("STATUS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 260, 58, 17);
        getContentPane().add(t3);
        t3.setBounds(280, 260, 160, 20);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        jButton2.setText("<<BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 370, 87, 31);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsag/images (29).jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 670, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try
{
        String name=t1.getText();
        String cost=t2.getText();
String status=t3.getText();
Class.forName("java.sql.DriverManager");
Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root","RRMPS");
Statement s=(Statement)c.createStatement();
String query="insert into allitems values('"+name+"',"+cost+",'"+status+"');";

JOptionPane.showMessageDialog(null,query);
s.executeUpdate(query);
JOptionPane.showMessageDialog(null,"items has been added");

    }
    catch (Exception e)
    {
JOptionPane.showMessageDialog(null,e);
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.dispose();
new menu().setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new items().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables

}
