package dsag;


import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mrd.java
 *
 * Created on Jan 1, 2002, 12:05:37 AM
 */

/**
 *
 * @author mukesh
 */
public class mrd extends javax.swing.JFrame {

    /** Creates new form mrd */
    public mrd() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MODIFY ROOM DETAILS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 20, 209, 31);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ROOM_NO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 140, 79, 17);

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ROOM TYPE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 190, 88, 17);

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 300, 0, 0);

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BOOKED");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 250, 65, 17);

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(270, 250, 140, 20);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(270, 180, 140, 20);
        getContentPane().add(t1);
        t1.setBounds(270, 130, 140, 20);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 310, 130, 31);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        jButton2.setText("MODIFY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 310, 130, 31);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 16));
        jButton3.setText("<<BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(480, 310, 130, 31);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsag/images (13).jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -60, 750, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root","RRMPS");
            Statement s=(Statement)c.createStatement();
            String quer="select * from room_details where r_no="+t1.getText()+";";
            ResultSet rs=s.executeQuery(quer);
            rs.next();

            String cu=rs.getString("r_type");
                        String e1= rs.getString("booked");
            s.executeQuery(quer);
            t2.setText(cu);

           
            t5.setText(e1);

        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ABCD","root","RRMPS");
            Statement s=(Statement)c.createStatement();
            String q="update room_details set r_type='"+t2.getText()+"',booked='"+t5.getText()+"';";
            s.executeUpdate(q);
            JOptionPane.showMessageDialog(null,"details updated");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new menu().setVisible(true);          // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mrd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables

}
